// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: remote/shellapi/shellapi.proto

package shellapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 盒子只会处于以下四种状态之一
type BoxStatus int32

const (
	// 此盒子当前未激活
	BoxStatus_DISABLED BoxStatus = 0
	// 内部状态，当激活的一瞬间会处于此状态
	// 此状态下会很快自动进入CONNECTING状态
	BoxStatus_ENABLED BoxStatus = 4
	// 正在连接中，此过程持续时间无法评估，
	// 可能瞬间结束也可能持续一两分钟(在确实可以连接上的前提下)
	BoxStatus_CONNECTING BoxStatus = 1
	// 此盒子已经可以正常使用
	BoxStatus_READY BoxStatus = 2
	// 确定无法连接，此时不会继续调度，需要客户端介入.
	// 客户端需要根据FailedStatus的具体值，进行修复。
	BoxStatus_FAILED BoxStatus = 3
)

// Enum value maps for BoxStatus.
var (
	BoxStatus_name = map[int32]string{
		0: "DISABLED",
		4: "ENABLED",
		1: "CONNECTING",
		2: "READY",
		3: "FAILED",
	}
	BoxStatus_value = map[string]int32{
		"DISABLED":   0,
		"ENABLED":    4,
		"CONNECTING": 1,
		"READY":      2,
		"FAILED":     3,
	}
)

func (x BoxStatus) Enum() *BoxStatus {
	p := new(BoxStatus)
	*p = x
	return p
}

func (x BoxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_shellapi_shellapi_proto_enumTypes[0].Descriptor()
}

func (BoxStatus) Type() protoreflect.EnumType {
	return &file_remote_shellapi_shellapi_proto_enumTypes[0]
}

func (x BoxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoxStatus.Descriptor instead.
func (BoxStatus) EnumDescriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{0}
}

// ------ 000 未知原因失败。其他所有状态都会有一个明确的处理方式，客户端UI需要根据具体的失败状态进行UI交互
// ------ 1xx 未进行login前的失败，如版本不匹配
// ------ 2xx login hserver未成功，如帐号密码错误、TFA失败、当前设备被管理员移除等
// ------ 3xx (hserver成功后)上层盒子系统异常，如数据盘需要解密、核心组件无法启动等
type FailedStatus int32

const (
	// 当前客户端无法处理此失败，直接提示failed reason
	// 比如hserver版本较高或较低，提供了一些当前hclient无法支持的失败状态
	FailedStatus_FAILED_UNKNOWN FailedStatus = 0
	// 调用LoginBox的过程中，此盒子的状态被其他API请求转换为disabled了
	FailedStatus_FAILED_LOCAL_DISABLED_BOX FailedStatus = 100
	// 调用LoginBox时使用了一个不存在的盒子名称。(若只是本地不盒子列表不存在此盒子，会自动添加到盒子列表)
	FailedStatus_FAILED_LOCAL_NO_SUCH_BOX_IN_THE_WORLD FailedStatus = 101
	// 使用LoginBox时，登录超时
	FailedStatus_FAILED_LOCAL_CONNECTING_TIMEOUT FailedStatus = 102
	// 当前设备已经被移除，请不要继续登录。仅在LoginBox时会出现此状态。且shellapi会自动删除此状态的配置信息
	FailedStatus_FAILED_LOCAL_DEVICE_HAS_BEEN_REMOVED FailedStatus = 103
	// 盒子未初始化，需要调用setupnewbox向horigin申请盒子名称以及配套资源
	FailedStatus_FAILED_LOGIN_HSERVER_NOT_INIT FailedStatus = 200
	// 当前登录信息不正确，需要调用ModifyBox设置新的auth信息
	FailedStatus_FAILED_LOGIN_INVALID_PASSWORD FailedStatus = 201
	// 当前客户端与服务器版本不匹配，无法连接，需要升级盒子系统或客户端软件
	FailedStatus_FAILED_LOGIN_MISMATCH_BOX_VERSION FailedStatus = 203
	// 需要进行两步验证
	FailedStatus_FAILED_LOGIN_TFA_REQUIRE FailedStatus = 204
	// 两步验证结果不通过
	FailedStatus_FAILED_LOGIN_TFA_FAILED FailedStatus = 205
	// 两步验证等待超时
	FailedStatus_FAILED_LOGIN_TFA_TIMEOUT                  FailedStatus = 206
	FailedStatus_FAILED_LOGIN_TFA_NO_TRUSTED_DEVICE_ONLINE FailedStatus = 207
	// 盒子系统处于异常状态，需要管理员介入修复
	FailedStatus_FAILED_BOXSYS_UNKNOWN_EXCEPTION FailedStatus = 301
	// 盒子系统处于数据盘等待解密状态，需要管理员输入磁盘密码
	FailedStatus_FAILED_BOXSYS_WAITING_DATADISK_DECRYPTION FailedStatus = 302
	// 盒子系统处于数据盘未初始化状态，需要管理员选择磁盘格式化方案，比如是否加密等
	FailedStatus_FAILED_BOXSYS_DATADISK_NOT_INIT FailedStatus = 303
)

// Enum value maps for FailedStatus.
var (
	FailedStatus_name = map[int32]string{
		0:   "FAILED_UNKNOWN",
		100: "FAILED_LOCAL_DISABLED_BOX",
		101: "FAILED_LOCAL_NO_SUCH_BOX_IN_THE_WORLD",
		102: "FAILED_LOCAL_CONNECTING_TIMEOUT",
		103: "FAILED_LOCAL_DEVICE_HAS_BEEN_REMOVED",
		200: "FAILED_LOGIN_HSERVER_NOT_INIT",
		201: "FAILED_LOGIN_INVALID_PASSWORD",
		203: "FAILED_LOGIN_MISMATCH_BOX_VERSION",
		204: "FAILED_LOGIN_TFA_REQUIRE",
		205: "FAILED_LOGIN_TFA_FAILED",
		206: "FAILED_LOGIN_TFA_TIMEOUT",
		207: "FAILED_LOGIN_TFA_NO_TRUSTED_DEVICE_ONLINE",
		301: "FAILED_BOXSYS_UNKNOWN_EXCEPTION",
		302: "FAILED_BOXSYS_WAITING_DATADISK_DECRYPTION",
		303: "FAILED_BOXSYS_DATADISK_NOT_INIT",
	}
	FailedStatus_value = map[string]int32{
		"FAILED_UNKNOWN":                            0,
		"FAILED_LOCAL_DISABLED_BOX":                 100,
		"FAILED_LOCAL_NO_SUCH_BOX_IN_THE_WORLD":     101,
		"FAILED_LOCAL_CONNECTING_TIMEOUT":           102,
		"FAILED_LOCAL_DEVICE_HAS_BEEN_REMOVED":      103,
		"FAILED_LOGIN_HSERVER_NOT_INIT":             200,
		"FAILED_LOGIN_INVALID_PASSWORD":             201,
		"FAILED_LOGIN_MISMATCH_BOX_VERSION":         203,
		"FAILED_LOGIN_TFA_REQUIRE":                  204,
		"FAILED_LOGIN_TFA_FAILED":                   205,
		"FAILED_LOGIN_TFA_TIMEOUT":                  206,
		"FAILED_LOGIN_TFA_NO_TRUSTED_DEVICE_ONLINE": 207,
		"FAILED_BOXSYS_UNKNOWN_EXCEPTION":           301,
		"FAILED_BOXSYS_WAITING_DATADISK_DECRYPTION": 302,
		"FAILED_BOXSYS_DATADISK_NOT_INIT":           303,
	}
)

func (x FailedStatus) Enum() *FailedStatus {
	p := new(FailedStatus)
	*p = x
	return p
}

func (x FailedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_shellapi_shellapi_proto_enumTypes[1].Descriptor()
}

func (FailedStatus) Type() protoreflect.EnumType {
	return &file_remote_shellapi_shellapi_proto_enumTypes[1]
}

func (x FailedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailedStatus.Descriptor instead.
func (FailedStatus) EnumDescriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{1}
}

type LowNetworkConnType int32

const (
	LowNetworkConnType_NOT_CONNECTED LowNetworkConnType = 0   //未建立连接
	LowNetworkConnType_BLE           LowNetworkConnType = 100 //通过蓝牙建立的慢速连接
	LowNetworkConnType_RELAY         LowNetworkConnType = 200 //通过中继建立的慢速连接
	LowNetworkConnType_NORMAL        LowNetworkConnType = 300 //正常连接，可能是通过多层或一层局域网也可能是互联网等方式建立的连接
	LowNetworkConnType_DIRECT        LowNetworkConnType = 400 //通过局域网等高速通道建立的连接
)

// Enum value maps for LowNetworkConnType.
var (
	LowNetworkConnType_name = map[int32]string{
		0:   "NOT_CONNECTED",
		100: "BLE",
		200: "RELAY",
		300: "NORMAL",
		400: "DIRECT",
	}
	LowNetworkConnType_value = map[string]int32{
		"NOT_CONNECTED": 0,
		"BLE":           100,
		"RELAY":         200,
		"NORMAL":        300,
		"DIRECT":        400,
	}
)

func (x LowNetworkConnType) Enum() *LowNetworkConnType {
	p := new(LowNetworkConnType)
	*p = x
	return p
}

func (x LowNetworkConnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LowNetworkConnType) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_shellapi_shellapi_proto_enumTypes[2].Descriptor()
}

func (LowNetworkConnType) Type() protoreflect.EnumType {
	return &file_remote_shellapi_shellapi_proto_enumTypes[2]
}

func (x LowNetworkConnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LowNetworkConnType.Descriptor instead.
func (LowNetworkConnType) EnumDescriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{2}
}

type ConnectNearbyBoxReply_Status int32

const (
	// 正在搜索
	ConnectNearbyBoxReply_Scanning ConnectNearbyBoxReply_Status = 0
	// 搜索到盒子，正在连接中
	ConnectNearbyBoxReply_Connecting ConnectNearbyBoxReply_Status = 1
	// 无法建立连接，具体原因看failed_reason字段
	ConnectNearbyBoxReply_Failed ConnectNearbyBoxReply_Status = 2
	// 成功建立连接， 此处的Connected仅代表libp2p层连接成功，
	// 调用者依旧需要使用`ModifyBox`之类的盒子管理接口来添加到盒子列表中
	ConnectNearbyBoxReply_Connected ConnectNearbyBoxReply_Status = 3
)

// Enum value maps for ConnectNearbyBoxReply_Status.
var (
	ConnectNearbyBoxReply_Status_name = map[int32]string{
		0: "Scanning",
		1: "Connecting",
		2: "Failed",
		3: "Connected",
	}
	ConnectNearbyBoxReply_Status_value = map[string]int32{
		"Scanning":   0,
		"Connecting": 1,
		"Failed":     2,
		"Connected":  3,
	}
)

func (x ConnectNearbyBoxReply_Status) Enum() *ConnectNearbyBoxReply_Status {
	p := new(ConnectNearbyBoxReply_Status)
	*p = x
	return p
}

func (x ConnectNearbyBoxReply_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectNearbyBoxReply_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_shellapi_shellapi_proto_enumTypes[3].Descriptor()
}

func (ConnectNearbyBoxReply_Status) Type() protoreflect.EnumType {
	return &file_remote_shellapi_shellapi_proto_enumTypes[3]
}

func (x ConnectNearbyBoxReply_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectNearbyBoxReply_Status.Descriptor instead.
func (ConnectNearbyBoxReply_Status) EnumDescriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{4, 0}
}

type LoginRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	BoxNameOrId string                 `protobuf:"bytes,1,opt,name=box_name_or_id,json=boxNameOrId,proto3" json:"box_name_or_id,omitempty"`
	UserName    string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPasswd  string                 `protobuf:"bytes,3,opt,name=user_passwd,json=userPasswd,proto3" json:"user_passwd,omitempty"`
	// 若为true则将此盒子设置为默认盒子，
	// 即使为false,但当前没有任何盒子的话，也会自动变为default_box
	AsDefaultBox bool `protobuf:"varint,4,opt,name=as_default_box,json=asDefaultBox,proto3" json:"as_default_box,omitempty"`
	// 最多等待多久
	MaxWaitSeconds int32   `protobuf:"varint,5,opt,name=max_wait_seconds,json=maxWaitSeconds,proto3" json:"max_wait_seconds,omitempty"`
	TfaCode        *string `protobuf:"bytes,6,opt,name=tfa_code,json=tfaCode,proto3,oneof" json:"tfa_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetBoxNameOrId() string {
	if x != nil {
		return x.BoxNameOrId
	}
	return ""
}

func (x *LoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginRequest) GetUserPasswd() string {
	if x != nil {
		return x.UserPasswd
	}
	return ""
}

func (x *LoginRequest) GetAsDefaultBox() bool {
	if x != nil {
		return x.AsDefaultBox
	}
	return false
}

func (x *LoginRequest) GetMaxWaitSeconds() int32 {
	if x != nil {
		return x.MaxWaitSeconds
	}
	return 0
}

func (x *LoginRequest) GetTfaCode() string {
	if x != nil && x.TfaCode != nil {
		return *x.TfaCode
	}
	return ""
}

type DialBoxServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoxId         string                 `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialBoxServiceRequest) Reset() {
	*x = DialBoxServiceRequest{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialBoxServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialBoxServiceRequest) ProtoMessage() {}

func (x *DialBoxServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialBoxServiceRequest.ProtoReflect.Descriptor instead.
func (*DialBoxServiceRequest) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{1}
}

func (x *DialBoxServiceRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *DialBoxServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type DialBoxServiceReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LocalProxyAddress string                 `protobuf:"bytes,1,opt,name=local_proxy_address,json=localProxyAddress,proto3" json:"local_proxy_address,omitempty"` //返回本地监听的临时地址
	ServiceExtraInfo  string                 `protobuf:"bytes,2,opt,name=service_extra_info,json=serviceExtraInfo,proto3" json:"service_extra_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DialBoxServiceReply) Reset() {
	*x = DialBoxServiceReply{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialBoxServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialBoxServiceReply) ProtoMessage() {}

func (x *DialBoxServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialBoxServiceReply.ProtoReflect.Descriptor instead.
func (*DialBoxServiceReply) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{2}
}

func (x *DialBoxServiceReply) GetLocalProxyAddress() string {
	if x != nil {
		return x.LocalProxyAddress
	}
	return ""
}

func (x *DialBoxServiceReply) GetServiceExtraInfo() string {
	if x != nil {
		return x.ServiceExtraInfo
	}
	return ""
}

type ConnectNearbyBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bsid          string                 `protobuf:"bytes,1,opt,name=bsid,proto3" json:"bsid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectNearbyBoxRequest) Reset() {
	*x = ConnectNearbyBoxRequest{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectNearbyBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectNearbyBoxRequest) ProtoMessage() {}

func (x *ConnectNearbyBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectNearbyBoxRequest.ProtoReflect.Descriptor instead.
func (*ConnectNearbyBoxRequest) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectNearbyBoxRequest) GetBsid() string {
	if x != nil {
		return x.Bsid
	}
	return ""
}

type ConnectNearbyBoxReply struct {
	state  protoimpl.MessageState       `protogen:"open.v1"`
	Status ConnectNearbyBoxReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=space.heiyu.hportal.shell.ConnectNearbyBoxReply_Status" json:"status,omitempty"`
	// 当status为Failed时，`failed_reason`提供更具体的信息
	FailedReason *string `protobuf:"bytes,2,opt,name=failed_reason,json=failedReason,proto3,oneof" json:"failed_reason,omitempty"`
	// 当status为Connected时，此字段为盒子的peer id
	BoxPeer *string `protobuf:"bytes,3,opt,name=box_peer,json=boxPeer,proto3,oneof" json:"box_peer,omitempty"`
	// 是否应该提示开启相关通道,此状态仅在状态为Scanning时有效
	ShouldEnableBle        bool `protobuf:"varint,4,opt,name=should_enable_ble,json=shouldEnableBle,proto3" json:"should_enable_ble,omitempty"`
	ShouldEnableWifidirect bool `protobuf:"varint,5,opt,name=should_enable_wifidirect,json=shouldEnableWifidirect,proto3" json:"should_enable_wifidirect,omitempty"`
	// 是否已初始化
	IsInitialized bool `protobuf:"varint,6,opt,name=is_initialized,json=isInitialized,proto3" json:"is_initialized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectNearbyBoxReply) Reset() {
	*x = ConnectNearbyBoxReply{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectNearbyBoxReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectNearbyBoxReply) ProtoMessage() {}

func (x *ConnectNearbyBoxReply) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectNearbyBoxReply.ProtoReflect.Descriptor instead.
func (*ConnectNearbyBoxReply) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectNearbyBoxReply) GetStatus() ConnectNearbyBoxReply_Status {
	if x != nil {
		return x.Status
	}
	return ConnectNearbyBoxReply_Scanning
}

func (x *ConnectNearbyBoxReply) GetFailedReason() string {
	if x != nil && x.FailedReason != nil {
		return *x.FailedReason
	}
	return ""
}

func (x *ConnectNearbyBoxReply) GetBoxPeer() string {
	if x != nil && x.BoxPeer != nil {
		return *x.BoxPeer
	}
	return ""
}

func (x *ConnectNearbyBoxReply) GetShouldEnableBle() bool {
	if x != nil {
		return x.ShouldEnableBle
	}
	return false
}

func (x *ConnectNearbyBoxReply) GetShouldEnableWifidirect() bool {
	if x != nil {
		return x.ShouldEnableWifidirect
	}
	return false
}

func (x *ConnectNearbyBoxReply) GetIsInitialized() bool {
	if x != nil {
		return x.IsInitialized
	}
	return false
}

// Deprecated: Marked as deprecated in remote/shellapi/shellapi.proto.
type DialTokenNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoxId         string                 `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"` //远端地址
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`          //目前只允许访问token类型网络,此字段必须写"token"
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`          //token的值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialTokenNetworkRequest) Reset() {
	*x = DialTokenNetworkRequest{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialTokenNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialTokenNetworkRequest) ProtoMessage() {}

func (x *DialTokenNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialTokenNetworkRequest.ProtoReflect.Descriptor instead.
func (*DialTokenNetworkRequest) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{5}
}

func (x *DialTokenNetworkRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *DialTokenNetworkRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DialTokenNetworkRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Deprecated: Marked as deprecated in remote/shellapi/shellapi.proto.
type DialTokenNetworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalEndpoint string                 `protobuf:"bytes,1,opt,name=local_endpoint,json=localEndpoint,proto3" json:"local_endpoint,omitempty"` //返回本地监听的临时地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialTokenNetworkReply) Reset() {
	*x = DialTokenNetworkReply{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialTokenNetworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialTokenNetworkReply) ProtoMessage() {}

func (x *DialTokenNetworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialTokenNetworkReply.ProtoReflect.Descriptor instead.
func (*DialTokenNetworkReply) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{6}
}

func (x *DialTokenNetworkReply) GetLocalEndpoint() string {
	if x != nil {
		return x.LocalEndpoint
	}
	return ""
}

type BoxID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxID) Reset() {
	*x = BoxID{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxID) ProtoMessage() {}

func (x *BoxID) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxID.ProtoReflect.Descriptor instead.
func (*BoxID) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{7}
}

func (x *BoxID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BoxSetting struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           //box_id
	Name    *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"` //box_name
	Enabled *bool                  `protobuf:"varint,3,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Auth    *BoxSetting_AuthInfo   `protobuf:"bytes,4,opt,name=auth,proto3,oneof" json:"auth,omitempty"`
	// 设置此盒子为默认盒子，会覆盖其他(如果有)默认盒子的配置
	// 第一个添加的盒子会自动成为默认盒子
	SetAsDefaultBox *bool   `protobuf:"varint,5,opt,name=set_as_default_box,json=setAsDefaultBox,proto3,oneof" json:"set_as_default_box,omitempty"`
	TfaCode         *string `protobuf:"bytes,6,opt,name=tfa_code,json=tfaCode,proto3,oneof" json:"tfa_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BoxSetting) Reset() {
	*x = BoxSetting{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxSetting) ProtoMessage() {}

func (x *BoxSetting) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxSetting.ProtoReflect.Descriptor instead.
func (*BoxSetting) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{8}
}

func (x *BoxSetting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoxSetting) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BoxSetting) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *BoxSetting) GetAuth() *BoxSetting_AuthInfo {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *BoxSetting) GetSetAsDefaultBox() bool {
	if x != nil && x.SetAsDefaultBox != nil {
		return *x.SetAsDefaultBox
	}
	return false
}

func (x *BoxSetting) GetTfaCode() string {
	if x != nil && x.TfaCode != nil {
		return *x.TfaCode
	}
	return ""
}

type BoxInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BoxId        string                 `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	BoxName      string                 `protobuf:"bytes,2,opt,name=box_name,json=boxName,proto3" json:"box_name,omitempty"`
	BoxHomeUrl   string                 `protobuf:"bytes,3,opt,name=box_home_url,json=boxHomeUrl,proto3" json:"box_home_url,omitempty"`
	BoxDomain    string                 `protobuf:"bytes,4,opt,name=box_domain,json=boxDomain,proto3" json:"box_domain,omitempty"`
	BoxVirtualIp string                 `protobuf:"bytes,5,opt,name=box_virtual_ip,json=boxVirtualIp,proto3" json:"box_virtual_ip,omitempty"`
	Status       BoxStatus              `protobuf:"varint,6,opt,name=status,proto3,enum=space.heiyu.hportal.shell.BoxStatus" json:"status,omitempty"`
	StatusReason string                 `protobuf:"bytes,7,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`
	FailedStatus *FailedStatus          `protobuf:"varint,8,opt,name=failed_status,json=failedStatus,proto3,enum=space.heiyu.hportal.shell.FailedStatus,oneof" json:"failed_status,omitempty"`
	LoginUser    string                 `protobuf:"bytes,9,opt,name=login_user,json=loginUser,proto3" json:"login_user,omitempty"`
	IsAdminLogin bool                   `protobuf:"varint,10,opt,name=is_admin_login,json=isAdminLogin,proto3" json:"is_admin_login,omitempty"`
	// 此盒子属于当前客户端的默认盒子
	IsDefaultBox bool `protobuf:"varint,11,opt,name=is_default_box,json=isDefaultBox,proto3" json:"is_default_box,omitempty"`
	// 底层网络的连接类型，如果是Relay/BLE这类则客户端一般需要进行提示并且限制访问流量要求大的应用
	ConnType      LowNetworkConnType `protobuf:"varint,12,opt,name=conn_type,json=connType,proto3,enum=space.heiyu.hportal.shell.LowNetworkConnType" json:"conn_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxInfo) Reset() {
	*x = BoxInfo{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxInfo) ProtoMessage() {}

func (x *BoxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxInfo.ProtoReflect.Descriptor instead.
func (*BoxInfo) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{9}
}

func (x *BoxInfo) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *BoxInfo) GetBoxName() string {
	if x != nil {
		return x.BoxName
	}
	return ""
}

func (x *BoxInfo) GetBoxHomeUrl() string {
	if x != nil {
		return x.BoxHomeUrl
	}
	return ""
}

func (x *BoxInfo) GetBoxDomain() string {
	if x != nil {
		return x.BoxDomain
	}
	return ""
}

func (x *BoxInfo) GetBoxVirtualIp() string {
	if x != nil {
		return x.BoxVirtualIp
	}
	return ""
}

func (x *BoxInfo) GetStatus() BoxStatus {
	if x != nil {
		return x.Status
	}
	return BoxStatus_DISABLED
}

func (x *BoxInfo) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *BoxInfo) GetFailedStatus() FailedStatus {
	if x != nil && x.FailedStatus != nil {
		return *x.FailedStatus
	}
	return FailedStatus_FAILED_UNKNOWN
}

func (x *BoxInfo) GetLoginUser() string {
	if x != nil {
		return x.LoginUser
	}
	return ""
}

func (x *BoxInfo) GetIsAdminLogin() bool {
	if x != nil {
		return x.IsAdminLogin
	}
	return false
}

func (x *BoxInfo) GetIsDefaultBox() bool {
	if x != nil {
		return x.IsDefaultBox
	}
	return false
}

func (x *BoxInfo) GetConnType() LowNetworkConnType {
	if x != nil {
		return x.ConnType
	}
	return LowNetworkConnType_NOT_CONNECTED
}

type BoxList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boxes         []*BoxInfo             `protobuf:"bytes,1,rep,name=boxes,proto3" json:"boxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxList) Reset() {
	*x = BoxList{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxList) ProtoMessage() {}

func (x *BoxList) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxList.ProtoReflect.Descriptor instead.
func (*BoxList) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{10}
}

func (x *BoxList) GetBoxes() []*BoxInfo {
	if x != nil {
		return x.Boxes
	}
	return nil
}

type ShellCoreInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TunIp string                 `protobuf:"bytes,2,opt,name=tun_ip,json=tunIp,proto3" json:"tun_ip,omitempty"`
	// 当前节点广播的地址列表
	LocalIps     []string `protobuf:"bytes,3,rep,name=local_ips,json=localIps,proto3" json:"local_ips,omitempty"`
	OriginServer string   `protobuf:"bytes,4,opt,name=origin_server,json=originServer,proto3" json:"origin_server,omitempty"`
	DeviceDomain string   `protobuf:"bytes,5,opt,name=device_domain,json=deviceDomain,proto3" json:"device_domain,omitempty"`
	Version      string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// 当前节点上的网卡地址列表
	IfceIps []string `protobuf:"bytes,7,rep,name=ifce_ips,json=ifceIps,proto3" json:"ifce_ips,omitempty"`
	// 当前节点上实际监听的地址列表
	ListenIps []string `protobuf:"bytes,8,rep,name=listen_ips,json=listenIps,proto3" json:"listen_ips,omitempty"`
	DeviceOs  string   `protobuf:"bytes,9,opt,name=device_os,json=deviceOs,proto3" json:"device_os,omitempty"`
	// 额外的调试信息
	DebugExtras   map[string]string `protobuf:"bytes,101,rep,name=debug_extras,json=debugExtras,proto3" json:"debug_extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCoreInfo) Reset() {
	*x = ShellCoreInfo{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCoreInfo) ProtoMessage() {}

func (x *ShellCoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCoreInfo.ProtoReflect.Descriptor instead.
func (*ShellCoreInfo) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{11}
}

func (x *ShellCoreInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShellCoreInfo) GetTunIp() string {
	if x != nil {
		return x.TunIp
	}
	return ""
}

func (x *ShellCoreInfo) GetLocalIps() []string {
	if x != nil {
		return x.LocalIps
	}
	return nil
}

func (x *ShellCoreInfo) GetOriginServer() string {
	if x != nil {
		return x.OriginServer
	}
	return ""
}

func (x *ShellCoreInfo) GetDeviceDomain() string {
	if x != nil {
		return x.DeviceDomain
	}
	return ""
}

func (x *ShellCoreInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ShellCoreInfo) GetIfceIps() []string {
	if x != nil {
		return x.IfceIps
	}
	return nil
}

func (x *ShellCoreInfo) GetListenIps() []string {
	if x != nil {
		return x.ListenIps
	}
	return nil
}

func (x *ShellCoreInfo) GetDeviceOs() string {
	if x != nil {
		return x.DeviceOs
	}
	return ""
}

func (x *ShellCoreInfo) GetDebugExtras() map[string]string {
	if x != nil {
		return x.DebugExtras
	}
	return nil
}

type UploadDebugInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 上传的服务器地址
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// 由用户提供的描述信息
	IssueContent string `protobuf:"bytes,2,opt,name=issue_content,json=issueContent,proto3" json:"issue_content,omitempty"`
	// 用户联系方式, 如手机号或邮箱地址
	Contact       string `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDebugInfoRequest) Reset() {
	*x = UploadDebugInfoRequest{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDebugInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDebugInfoRequest) ProtoMessage() {}

func (x *UploadDebugInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDebugInfoRequest.ProtoReflect.Descriptor instead.
func (*UploadDebugInfoRequest) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{12}
}

func (x *UploadDebugInfoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadDebugInfoRequest) GetIssueContent() string {
	if x != nil {
		return x.IssueContent
	}
	return ""
}

func (x *UploadDebugInfoRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type UploadDebugInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDebugInfoResponse) Reset() {
	*x = UploadDebugInfoResponse{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDebugInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDebugInfoResponse) ProtoMessage() {}

func (x *UploadDebugInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDebugInfoResponse.ProtoReflect.Descriptor instead.
func (*UploadDebugInfoResponse) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{13}
}

func (x *UploadDebugInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BoxSetting_AuthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordHash  *string                `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3,oneof" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxSetting_AuthInfo) Reset() {
	*x = BoxSetting_AuthInfo{}
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxSetting_AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxSetting_AuthInfo) ProtoMessage() {}

func (x *BoxSetting_AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_remote_shellapi_shellapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxSetting_AuthInfo.ProtoReflect.Descriptor instead.
func (*BoxSetting_AuthInfo) Descriptor() ([]byte, []int) {
	return file_remote_shellapi_shellapi_proto_rawDescGZIP(), []int{8, 0}
}

func (x *BoxSetting_AuthInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BoxSetting_AuthInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BoxSetting_AuthInfo) GetPasswordHash() string {
	if x != nil && x.PasswordHash != nil {
		return *x.PasswordHash
	}
	return ""
}

var File_remote_shellapi_shellapi_proto protoreflect.FileDescriptor

const file_remote_shellapi_shellapi_proto_rawDesc = "" +
	"\n" +
	"\x1eremote/shellapi/shellapi.proto\x12\x19space.heiyu.hportal.shell\x1a\x1bgoogle/protobuf/empty.proto\"\xee\x01\n" +
	"\fLoginRequest\x12#\n" +
	"\x0ebox_name_or_id\x18\x01 \x01(\tR\vboxNameOrId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1f\n" +
	"\vuser_passwd\x18\x03 \x01(\tR\n" +
	"userPasswd\x12$\n" +
	"\x0eas_default_box\x18\x04 \x01(\bR\fasDefaultBox\x12(\n" +
	"\x10max_wait_seconds\x18\x05 \x01(\x05R\x0emaxWaitSeconds\x12\x1e\n" +
	"\btfa_code\x18\x06 \x01(\tH\x00R\atfaCode\x88\x01\x01B\v\n" +
	"\t_tfa_code\"Q\n" +
	"\x15DialBoxServiceRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\"s\n" +
	"\x13DialBoxServiceReply\x12.\n" +
	"\x13local_proxy_address\x18\x01 \x01(\tR\x11localProxyAddress\x12,\n" +
	"\x12service_extra_info\x18\x02 \x01(\tR\x10serviceExtraInfo\"-\n" +
	"\x17ConnectNearbyBoxRequest\x12\x12\n" +
	"\x04bsid\x18\x01 \x01(\tR\x04bsid\"\xa1\x03\n" +
	"\x15ConnectNearbyBoxReply\x12O\n" +
	"\x06status\x18\x01 \x01(\x0e27.space.heiyu.hportal.shell.ConnectNearbyBoxReply.StatusR\x06status\x12(\n" +
	"\rfailed_reason\x18\x02 \x01(\tH\x00R\ffailedReason\x88\x01\x01\x12\x1e\n" +
	"\bbox_peer\x18\x03 \x01(\tH\x01R\aboxPeer\x88\x01\x01\x12*\n" +
	"\x11should_enable_ble\x18\x04 \x01(\bR\x0fshouldEnableBle\x128\n" +
	"\x18should_enable_wifidirect\x18\x05 \x01(\bR\x16shouldEnableWifidirect\x12%\n" +
	"\x0eis_initialized\x18\x06 \x01(\bR\risInitialized\"A\n" +
	"\x06Status\x12\f\n" +
	"\bScanning\x10\x00\x12\x0e\n" +
	"\n" +
	"Connecting\x10\x01\x12\n" +
	"\n" +
	"\x06Failed\x10\x02\x12\r\n" +
	"\tConnected\x10\x03B\x10\n" +
	"\x0e_failed_reasonB\v\n" +
	"\t_box_peer\"h\n" +
	"\x17DialTokenNetworkRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress:\x02\x18\x01\"B\n" +
	"\x15DialTokenNetworkReply\x12%\n" +
	"\x0elocal_endpoint\x18\x01 \x01(\tR\rlocalEndpoint:\x02\x18\x01\"\x17\n" +
	"\x05BoxID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa9\x03\n" +
	"\n" +
	"BoxSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x03 \x01(\bH\x01R\aenabled\x88\x01\x01\x12G\n" +
	"\x04auth\x18\x04 \x01(\v2..space.heiyu.hportal.shell.BoxSetting.AuthInfoH\x02R\x04auth\x88\x01\x01\x120\n" +
	"\x12set_as_default_box\x18\x05 \x01(\bH\x03R\x0fsetAsDefaultBox\x88\x01\x01\x12\x1e\n" +
	"\btfa_code\x18\x06 \x01(\tH\x04R\atfaCode\x88\x01\x01\x1av\n" +
	"\bAuthInfo\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12(\n" +
	"\rpassword_hash\x18\x03 \x01(\tH\x00R\fpasswordHash\x88\x01\x01B\x10\n" +
	"\x0e_password_hashB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_enabledB\a\n" +
	"\x05_authB\x15\n" +
	"\x13_set_as_default_boxB\v\n" +
	"\t_tfa_code\"\xa1\x04\n" +
	"\aBoxInfo\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x19\n" +
	"\bbox_name\x18\x02 \x01(\tR\aboxName\x12 \n" +
	"\fbox_home_url\x18\x03 \x01(\tR\n" +
	"boxHomeUrl\x12\x1d\n" +
	"\n" +
	"box_domain\x18\x04 \x01(\tR\tboxDomain\x12$\n" +
	"\x0ebox_virtual_ip\x18\x05 \x01(\tR\fboxVirtualIp\x12<\n" +
	"\x06status\x18\x06 \x01(\x0e2$.space.heiyu.hportal.shell.BoxStatusR\x06status\x12#\n" +
	"\rstatus_reason\x18\a \x01(\tR\fstatusReason\x12Q\n" +
	"\rfailed_status\x18\b \x01(\x0e2'.space.heiyu.hportal.shell.FailedStatusH\x00R\ffailedStatus\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"login_user\x18\t \x01(\tR\tloginUser\x12$\n" +
	"\x0eis_admin_login\x18\n" +
	" \x01(\bR\fisAdminLogin\x12$\n" +
	"\x0eis_default_box\x18\v \x01(\bR\fisDefaultBox\x12J\n" +
	"\tconn_type\x18\f \x01(\x0e2-.space.heiyu.hportal.shell.LowNetworkConnTypeR\bconnTypeB\x10\n" +
	"\x0e_failed_status\"C\n" +
	"\aBoxList\x128\n" +
	"\x05boxes\x18\x01 \x03(\v2\".space.heiyu.hportal.shell.BoxInfoR\x05boxes\"\xac\x03\n" +
	"\rShellCoreInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06tun_ip\x18\x02 \x01(\tR\x05tunIp\x12\x1b\n" +
	"\tlocal_ips\x18\x03 \x03(\tR\blocalIps\x12#\n" +
	"\rorigin_server\x18\x04 \x01(\tR\foriginServer\x12#\n" +
	"\rdevice_domain\x18\x05 \x01(\tR\fdeviceDomain\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x19\n" +
	"\bifce_ips\x18\a \x03(\tR\aifceIps\x12\x1d\n" +
	"\n" +
	"listen_ips\x18\b \x03(\tR\tlistenIps\x12\x1b\n" +
	"\tdevice_os\x18\t \x01(\tR\bdeviceOs\x12\\\n" +
	"\fdebug_extras\x18e \x03(\v29.space.heiyu.hportal.shell.ShellCoreInfo.DebugExtrasEntryR\vdebugExtras\x1a>\n" +
	"\x10DebugExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x16UploadDebugInfoRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12#\n" +
	"\rissue_content\x18\x02 \x01(\tR\fissueContent\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\")\n" +
	"\x17UploadDebugInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*M\n" +
	"\tBoxStatus\x12\f\n" +
	"\bDISABLED\x10\x00\x12\v\n" +
	"\aENABLED\x10\x04\x12\x0e\n" +
	"\n" +
	"CONNECTING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03*\xb3\x04\n" +
	"\fFailedStatus\x12\x12\n" +
	"\x0eFAILED_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19FAILED_LOCAL_DISABLED_BOX\x10d\x12)\n" +
	"%FAILED_LOCAL_NO_SUCH_BOX_IN_THE_WORLD\x10e\x12#\n" +
	"\x1fFAILED_LOCAL_CONNECTING_TIMEOUT\x10f\x12(\n" +
	"$FAILED_LOCAL_DEVICE_HAS_BEEN_REMOVED\x10g\x12\"\n" +
	"\x1dFAILED_LOGIN_HSERVER_NOT_INIT\x10\xc8\x01\x12\"\n" +
	"\x1dFAILED_LOGIN_INVALID_PASSWORD\x10\xc9\x01\x12&\n" +
	"!FAILED_LOGIN_MISMATCH_BOX_VERSION\x10\xcb\x01\x12\x1d\n" +
	"\x18FAILED_LOGIN_TFA_REQUIRE\x10\xcc\x01\x12\x1c\n" +
	"\x17FAILED_LOGIN_TFA_FAILED\x10\xcd\x01\x12\x1d\n" +
	"\x18FAILED_LOGIN_TFA_TIMEOUT\x10\xce\x01\x12.\n" +
	")FAILED_LOGIN_TFA_NO_TRUSTED_DEVICE_ONLINE\x10\xcf\x01\x12$\n" +
	"\x1fFAILED_BOXSYS_UNKNOWN_EXCEPTION\x10\xad\x02\x12.\n" +
	")FAILED_BOXSYS_WAITING_DATADISK_DECRYPTION\x10\xae\x02\x12$\n" +
	"\x1fFAILED_BOXSYS_DATADISK_NOT_INIT\x10\xaf\x02*V\n" +
	"\x12LowNetworkConnType\x12\x11\n" +
	"\rNOT_CONNECTED\x10\x00\x12\a\n" +
	"\x03BLE\x10d\x12\n" +
	"\n" +
	"\x05RELAY\x10\xc8\x01\x12\v\n" +
	"\x06NORMAL\x10\xac\x02\x12\v\n" +
	"\x06DIRECT\x10\x90\x032\xd0\a\n" +
	"\tShellCore\x12H\n" +
	"\fDelBoxConfig\x12 .space.heiyu.hportal.shell.BoxID\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x0fModifyBoxConfig\x12%.space.heiyu.hportal.shell.BoxSetting\x1a\x16.google.protobuf.Empty\x12Y\n" +
	"\bLoginBox\x12'.space.heiyu.hportal.shell.LoginRequest\x1a\".space.heiyu.hportal.shell.BoxInfo0\x01\x12J\n" +
	"\fQueryBoxList\x12\x16.google.protobuf.Empty\x1a\".space.heiyu.hportal.shell.BoxList\x12V\n" +
	"\x12QueryShellCoreInfo\x12\x16.google.protobuf.Empty\x1a(.space.heiyu.hportal.shell.ShellCoreInfo\x12x\n" +
	"\x0fUploadDebugInfo\x121.space.heiyu.hportal.shell.UploadDebugInfoRequest\x1a2.space.heiyu.hportal.shell.UploadDebugInfoResponse\x12z\n" +
	"\x10ConnectNearbyBox\x122.space.heiyu.hportal.shell.ConnectNearbyBoxRequest\x1a0.space.heiyu.hportal.shell.ConnectNearbyBoxReply0\x01\x12t\n" +
	"\x0eDialBoxService\x120.space.heiyu.hportal.shell.DialBoxServiceRequest\x1a..space.heiyu.hportal.shell.DialBoxServiceReply0\x01\x12;\n" +
	"\x04Exit\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x03\x88\x02\x01\x12\x7f\n" +
	"\x10DialTokenNetwork\x122.space.heiyu.hportal.shell.DialTokenNetworkRequest\x1a0.space.heiyu.hportal.shell.DialTokenNetworkReply\"\x03\x88\x02\x010\x01B2Z0github.com/lib-x/lpk-go/remote/shellapi;shellapib\x06proto3"

var (
	file_remote_shellapi_shellapi_proto_rawDescOnce sync.Once
	file_remote_shellapi_shellapi_proto_rawDescData []byte
)

func file_remote_shellapi_shellapi_proto_rawDescGZIP() []byte {
	file_remote_shellapi_shellapi_proto_rawDescOnce.Do(func() {
		file_remote_shellapi_shellapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_shellapi_shellapi_proto_rawDesc), len(file_remote_shellapi_shellapi_proto_rawDesc)))
	})
	return file_remote_shellapi_shellapi_proto_rawDescData
}

var file_remote_shellapi_shellapi_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_remote_shellapi_shellapi_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_remote_shellapi_shellapi_proto_goTypes = []any{
	(BoxStatus)(0),                    // 0: space.heiyu.hportal.shell.BoxStatus
	(FailedStatus)(0),                 // 1: space.heiyu.hportal.shell.FailedStatus
	(LowNetworkConnType)(0),           // 2: space.heiyu.hportal.shell.LowNetworkConnType
	(ConnectNearbyBoxReply_Status)(0), // 3: space.heiyu.hportal.shell.ConnectNearbyBoxReply.Status
	(*LoginRequest)(nil),              // 4: space.heiyu.hportal.shell.LoginRequest
	(*DialBoxServiceRequest)(nil),     // 5: space.heiyu.hportal.shell.DialBoxServiceRequest
	(*DialBoxServiceReply)(nil),       // 6: space.heiyu.hportal.shell.DialBoxServiceReply
	(*ConnectNearbyBoxRequest)(nil),   // 7: space.heiyu.hportal.shell.ConnectNearbyBoxRequest
	(*ConnectNearbyBoxReply)(nil),     // 8: space.heiyu.hportal.shell.ConnectNearbyBoxReply
	(*DialTokenNetworkRequest)(nil),   // 9: space.heiyu.hportal.shell.DialTokenNetworkRequest
	(*DialTokenNetworkReply)(nil),     // 10: space.heiyu.hportal.shell.DialTokenNetworkReply
	(*BoxID)(nil),                     // 11: space.heiyu.hportal.shell.BoxID
	(*BoxSetting)(nil),                // 12: space.heiyu.hportal.shell.BoxSetting
	(*BoxInfo)(nil),                   // 13: space.heiyu.hportal.shell.BoxInfo
	(*BoxList)(nil),                   // 14: space.heiyu.hportal.shell.BoxList
	(*ShellCoreInfo)(nil),             // 15: space.heiyu.hportal.shell.ShellCoreInfo
	(*UploadDebugInfoRequest)(nil),    // 16: space.heiyu.hportal.shell.UploadDebugInfoRequest
	(*UploadDebugInfoResponse)(nil),   // 17: space.heiyu.hportal.shell.UploadDebugInfoResponse
	(*BoxSetting_AuthInfo)(nil),       // 18: space.heiyu.hportal.shell.BoxSetting.AuthInfo
	nil,                               // 19: space.heiyu.hportal.shell.ShellCoreInfo.DebugExtrasEntry
	(*emptypb.Empty)(nil),             // 20: google.protobuf.Empty
}
var file_remote_shellapi_shellapi_proto_depIdxs = []int32{
	3,  // 0: space.heiyu.hportal.shell.ConnectNearbyBoxReply.status:type_name -> space.heiyu.hportal.shell.ConnectNearbyBoxReply.Status
	18, // 1: space.heiyu.hportal.shell.BoxSetting.auth:type_name -> space.heiyu.hportal.shell.BoxSetting.AuthInfo
	0,  // 2: space.heiyu.hportal.shell.BoxInfo.status:type_name -> space.heiyu.hportal.shell.BoxStatus
	1,  // 3: space.heiyu.hportal.shell.BoxInfo.failed_status:type_name -> space.heiyu.hportal.shell.FailedStatus
	2,  // 4: space.heiyu.hportal.shell.BoxInfo.conn_type:type_name -> space.heiyu.hportal.shell.LowNetworkConnType
	13, // 5: space.heiyu.hportal.shell.BoxList.boxes:type_name -> space.heiyu.hportal.shell.BoxInfo
	19, // 6: space.heiyu.hportal.shell.ShellCoreInfo.debug_extras:type_name -> space.heiyu.hportal.shell.ShellCoreInfo.DebugExtrasEntry
	11, // 7: space.heiyu.hportal.shell.ShellCore.DelBoxConfig:input_type -> space.heiyu.hportal.shell.BoxID
	12, // 8: space.heiyu.hportal.shell.ShellCore.ModifyBoxConfig:input_type -> space.heiyu.hportal.shell.BoxSetting
	4,  // 9: space.heiyu.hportal.shell.ShellCore.LoginBox:input_type -> space.heiyu.hportal.shell.LoginRequest
	20, // 10: space.heiyu.hportal.shell.ShellCore.QueryBoxList:input_type -> google.protobuf.Empty
	20, // 11: space.heiyu.hportal.shell.ShellCore.QueryShellCoreInfo:input_type -> google.protobuf.Empty
	16, // 12: space.heiyu.hportal.shell.ShellCore.UploadDebugInfo:input_type -> space.heiyu.hportal.shell.UploadDebugInfoRequest
	7,  // 13: space.heiyu.hportal.shell.ShellCore.ConnectNearbyBox:input_type -> space.heiyu.hportal.shell.ConnectNearbyBoxRequest
	5,  // 14: space.heiyu.hportal.shell.ShellCore.DialBoxService:input_type -> space.heiyu.hportal.shell.DialBoxServiceRequest
	20, // 15: space.heiyu.hportal.shell.ShellCore.Exit:input_type -> google.protobuf.Empty
	9,  // 16: space.heiyu.hportal.shell.ShellCore.DialTokenNetwork:input_type -> space.heiyu.hportal.shell.DialTokenNetworkRequest
	20, // 17: space.heiyu.hportal.shell.ShellCore.DelBoxConfig:output_type -> google.protobuf.Empty
	20, // 18: space.heiyu.hportal.shell.ShellCore.ModifyBoxConfig:output_type -> google.protobuf.Empty
	13, // 19: space.heiyu.hportal.shell.ShellCore.LoginBox:output_type -> space.heiyu.hportal.shell.BoxInfo
	14, // 20: space.heiyu.hportal.shell.ShellCore.QueryBoxList:output_type -> space.heiyu.hportal.shell.BoxList
	15, // 21: space.heiyu.hportal.shell.ShellCore.QueryShellCoreInfo:output_type -> space.heiyu.hportal.shell.ShellCoreInfo
	17, // 22: space.heiyu.hportal.shell.ShellCore.UploadDebugInfo:output_type -> space.heiyu.hportal.shell.UploadDebugInfoResponse
	8,  // 23: space.heiyu.hportal.shell.ShellCore.ConnectNearbyBox:output_type -> space.heiyu.hportal.shell.ConnectNearbyBoxReply
	6,  // 24: space.heiyu.hportal.shell.ShellCore.DialBoxService:output_type -> space.heiyu.hportal.shell.DialBoxServiceReply
	20, // 25: space.heiyu.hportal.shell.ShellCore.Exit:output_type -> google.protobuf.Empty
	10, // 26: space.heiyu.hportal.shell.ShellCore.DialTokenNetwork:output_type -> space.heiyu.hportal.shell.DialTokenNetworkReply
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_remote_shellapi_shellapi_proto_init() }
func file_remote_shellapi_shellapi_proto_init() {
	if File_remote_shellapi_shellapi_proto != nil {
		return
	}
	file_remote_shellapi_shellapi_proto_msgTypes[0].OneofWrappers = []any{}
	file_remote_shellapi_shellapi_proto_msgTypes[4].OneofWrappers = []any{}
	file_remote_shellapi_shellapi_proto_msgTypes[8].OneofWrappers = []any{}
	file_remote_shellapi_shellapi_proto_msgTypes[9].OneofWrappers = []any{}
	file_remote_shellapi_shellapi_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_shellapi_shellapi_proto_rawDesc), len(file_remote_shellapi_shellapi_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_shellapi_shellapi_proto_goTypes,
		DependencyIndexes: file_remote_shellapi_shellapi_proto_depIdxs,
		EnumInfos:         file_remote_shellapi_shellapi_proto_enumTypes,
		MessageInfos:      file_remote_shellapi_shellapi_proto_msgTypes,
	}.Build()
	File_remote_shellapi_shellapi_proto = out.File
	file_remote_shellapi_shellapi_proto_goTypes = nil
	file_remote_shellapi_shellapi_proto_depIdxs = nil
}
