// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: remote/shellapi/shellapi.proto

package shellapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShellCore_DelBoxConfig_FullMethodName       = "/space.heiyu.hportal.shell.ShellCore/DelBoxConfig"
	ShellCore_ModifyBoxConfig_FullMethodName    = "/space.heiyu.hportal.shell.ShellCore/ModifyBoxConfig"
	ShellCore_LoginBox_FullMethodName           = "/space.heiyu.hportal.shell.ShellCore/LoginBox"
	ShellCore_QueryBoxList_FullMethodName       = "/space.heiyu.hportal.shell.ShellCore/QueryBoxList"
	ShellCore_QueryShellCoreInfo_FullMethodName = "/space.heiyu.hportal.shell.ShellCore/QueryShellCoreInfo"
	ShellCore_UploadDebugInfo_FullMethodName    = "/space.heiyu.hportal.shell.ShellCore/UploadDebugInfo"
	ShellCore_ConnectNearbyBox_FullMethodName   = "/space.heiyu.hportal.shell.ShellCore/ConnectNearbyBox"
	ShellCore_DialBoxService_FullMethodName     = "/space.heiyu.hportal.shell.ShellCore/DialBoxService"
	ShellCore_Exit_FullMethodName               = "/space.heiyu.hportal.shell.ShellCore/Exit"
	ShellCore_DialTokenNetwork_FullMethodName   = "/space.heiyu.hportal.shell.ShellCore/DialTokenNetwork"
)

// ShellCoreClient is the client API for ShellCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 此接口为hclient&hserver曝露给管理界面、命令行客户端等使用的API
type ShellCoreClient interface {
	// 删除盒子
	DelBoxConfig(ctx context.Context, in *BoxID, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 添加、修改盒子的登录信息、开启、关闭盒子等
	// 如果是登录新盒子，可以直接使用LoginBox这个接口，一次性处理ModifyBoxConfig和等待成功操作
	ModifyBoxConfig(ctx context.Context, in *BoxSetting, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 阻塞请求登录一个具体盒子，以下几种情况下会结束整个请求
	// 1. 请求超时。(由LoginRequest中的max_wait_seconds决定)
	// 2. 结果为非connecting状态
	//
	// 连接中的状态会通过stream返回
	LoginBox(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BoxInfo], error)
	// 查询当前盒子列表的状态
	QueryBoxList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BoxList, error)
	// 查询shellcore本身的一些信息
	QueryShellCoreInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ShellCoreInfo, error)
	// 将日志以及额外的调试信息上传到官方服务器, 主要给最终用户点击上传日志时使用
	UploadDebugInfo(ctx context.Context, in *UploadDebugInfoRequest, opts ...grpc.CallOption) (*UploadDebugInfoResponse, error)
	// 基于BSID与附近的盒子建立"近场"直连通讯
	// 成功连接后，hclient与hserver可以正常通讯，但底层可能是ble之类的慢速通道
	// 后续会在合适的时候自动使用此通道进行连接(优先级较低)
	ConnectNearbyBox(ctx context.Context, in *ConnectNearbyBoxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectNearbyBoxReply], error)
	// 请求访问(盒子里)通过sysbridge/RegisterBoxService注册的服务
	//
	//   - 在成功连接上请求的盒子后会返回本地的代理监听地址
	//   - 当调用者关闭本请求时或会自动释放相关资源
	//   - 返回的监听地址为127.0.0.1上的随机端口
	//   - 若盒子服务在开始存在，但在此函数中途丢失或出现网络错误
	//     本函数不会主动终止，调用者应该根据实际代理服务的情况来决定是否应该主动结束DialBoxService
	DialBoxService(ctx context.Context, in *DialBoxServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DialBoxServiceReply], error)
	// Deprecated: Do not use.
	// 使shellcore进程退出.  只有PC上有意义，优先考虑在client侧处理
	Exit(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deprecated: Do not use.
	DialTokenNetwork(ctx context.Context, in *DialTokenNetworkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DialTokenNetworkReply], error)
}

type shellCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewShellCoreClient(cc grpc.ClientConnInterface) ShellCoreClient {
	return &shellCoreClient{cc}
}

func (c *shellCoreClient) DelBoxConfig(ctx context.Context, in *BoxID, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShellCore_DelBoxConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellCoreClient) ModifyBoxConfig(ctx context.Context, in *BoxSetting, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShellCore_ModifyBoxConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellCoreClient) LoginBox(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BoxInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellCore_ServiceDesc.Streams[0], ShellCore_LoginBox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoginRequest, BoxInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellCore_LoginBoxClient = grpc.ServerStreamingClient[BoxInfo]

func (c *shellCoreClient) QueryBoxList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BoxList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoxList)
	err := c.cc.Invoke(ctx, ShellCore_QueryBoxList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellCoreClient) QueryShellCoreInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ShellCoreInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShellCoreInfo)
	err := c.cc.Invoke(ctx, ShellCore_QueryShellCoreInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellCoreClient) UploadDebugInfo(ctx context.Context, in *UploadDebugInfoRequest, opts ...grpc.CallOption) (*UploadDebugInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDebugInfoResponse)
	err := c.cc.Invoke(ctx, ShellCore_UploadDebugInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellCoreClient) ConnectNearbyBox(ctx context.Context, in *ConnectNearbyBoxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectNearbyBoxReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellCore_ServiceDesc.Streams[1], ShellCore_ConnectNearbyBox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectNearbyBoxRequest, ConnectNearbyBoxReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellCore_ConnectNearbyBoxClient = grpc.ServerStreamingClient[ConnectNearbyBoxReply]

func (c *shellCoreClient) DialBoxService(ctx context.Context, in *DialBoxServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DialBoxServiceReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellCore_ServiceDesc.Streams[2], ShellCore_DialBoxService_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DialBoxServiceRequest, DialBoxServiceReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellCore_DialBoxServiceClient = grpc.ServerStreamingClient[DialBoxServiceReply]

// Deprecated: Do not use.
func (c *shellCoreClient) Exit(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShellCore_Exit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *shellCoreClient) DialTokenNetwork(ctx context.Context, in *DialTokenNetworkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DialTokenNetworkReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellCore_ServiceDesc.Streams[3], ShellCore_DialTokenNetwork_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DialTokenNetworkRequest, DialTokenNetworkReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellCore_DialTokenNetworkClient = grpc.ServerStreamingClient[DialTokenNetworkReply]

// ShellCoreServer is the server API for ShellCore service.
// All implementations must embed UnimplementedShellCoreServer
// for forward compatibility.
//
// 此接口为hclient&hserver曝露给管理界面、命令行客户端等使用的API
type ShellCoreServer interface {
	// 删除盒子
	DelBoxConfig(context.Context, *BoxID) (*emptypb.Empty, error)
	// 添加、修改盒子的登录信息、开启、关闭盒子等
	// 如果是登录新盒子，可以直接使用LoginBox这个接口，一次性处理ModifyBoxConfig和等待成功操作
	ModifyBoxConfig(context.Context, *BoxSetting) (*emptypb.Empty, error)
	// 阻塞请求登录一个具体盒子，以下几种情况下会结束整个请求
	// 1. 请求超时。(由LoginRequest中的max_wait_seconds决定)
	// 2. 结果为非connecting状态
	//
	// 连接中的状态会通过stream返回
	LoginBox(*LoginRequest, grpc.ServerStreamingServer[BoxInfo]) error
	// 查询当前盒子列表的状态
	QueryBoxList(context.Context, *emptypb.Empty) (*BoxList, error)
	// 查询shellcore本身的一些信息
	QueryShellCoreInfo(context.Context, *emptypb.Empty) (*ShellCoreInfo, error)
	// 将日志以及额外的调试信息上传到官方服务器, 主要给最终用户点击上传日志时使用
	UploadDebugInfo(context.Context, *UploadDebugInfoRequest) (*UploadDebugInfoResponse, error)
	// 基于BSID与附近的盒子建立"近场"直连通讯
	// 成功连接后，hclient与hserver可以正常通讯，但底层可能是ble之类的慢速通道
	// 后续会在合适的时候自动使用此通道进行连接(优先级较低)
	ConnectNearbyBox(*ConnectNearbyBoxRequest, grpc.ServerStreamingServer[ConnectNearbyBoxReply]) error
	// 请求访问(盒子里)通过sysbridge/RegisterBoxService注册的服务
	//
	//   - 在成功连接上请求的盒子后会返回本地的代理监听地址
	//   - 当调用者关闭本请求时或会自动释放相关资源
	//   - 返回的监听地址为127.0.0.1上的随机端口
	//   - 若盒子服务在开始存在，但在此函数中途丢失或出现网络错误
	//     本函数不会主动终止，调用者应该根据实际代理服务的情况来决定是否应该主动结束DialBoxService
	DialBoxService(*DialBoxServiceRequest, grpc.ServerStreamingServer[DialBoxServiceReply]) error
	// Deprecated: Do not use.
	// 使shellcore进程退出.  只有PC上有意义，优先考虑在client侧处理
	Exit(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Deprecated: Do not use.
	DialTokenNetwork(*DialTokenNetworkRequest, grpc.ServerStreamingServer[DialTokenNetworkReply]) error
	mustEmbedUnimplementedShellCoreServer()
}

// UnimplementedShellCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShellCoreServer struct{}

func (UnimplementedShellCoreServer) DelBoxConfig(context.Context, *BoxID) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelBoxConfig not implemented")
}
func (UnimplementedShellCoreServer) ModifyBoxConfig(context.Context, *BoxSetting) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyBoxConfig not implemented")
}
func (UnimplementedShellCoreServer) LoginBox(*LoginRequest, grpc.ServerStreamingServer[BoxInfo]) error {
	return status.Errorf(codes.Unimplemented, "method LoginBox not implemented")
}
func (UnimplementedShellCoreServer) QueryBoxList(context.Context, *emptypb.Empty) (*BoxList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBoxList not implemented")
}
func (UnimplementedShellCoreServer) QueryShellCoreInfo(context.Context, *emptypb.Empty) (*ShellCoreInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryShellCoreInfo not implemented")
}
func (UnimplementedShellCoreServer) UploadDebugInfo(context.Context, *UploadDebugInfoRequest) (*UploadDebugInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDebugInfo not implemented")
}
func (UnimplementedShellCoreServer) ConnectNearbyBox(*ConnectNearbyBoxRequest, grpc.ServerStreamingServer[ConnectNearbyBoxReply]) error {
	return status.Errorf(codes.Unimplemented, "method ConnectNearbyBox not implemented")
}
func (UnimplementedShellCoreServer) DialBoxService(*DialBoxServiceRequest, grpc.ServerStreamingServer[DialBoxServiceReply]) error {
	return status.Errorf(codes.Unimplemented, "method DialBoxService not implemented")
}
func (UnimplementedShellCoreServer) Exit(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exit not implemented")
}
func (UnimplementedShellCoreServer) DialTokenNetwork(*DialTokenNetworkRequest, grpc.ServerStreamingServer[DialTokenNetworkReply]) error {
	return status.Errorf(codes.Unimplemented, "method DialTokenNetwork not implemented")
}
func (UnimplementedShellCoreServer) mustEmbedUnimplementedShellCoreServer() {}
func (UnimplementedShellCoreServer) testEmbeddedByValue()                   {}

// UnsafeShellCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShellCoreServer will
// result in compilation errors.
type UnsafeShellCoreServer interface {
	mustEmbedUnimplementedShellCoreServer()
}

func RegisterShellCoreServer(s grpc.ServiceRegistrar, srv ShellCoreServer) {
	// If the following call pancis, it indicates UnimplementedShellCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShellCore_ServiceDesc, srv)
}

func _ShellCore_DelBoxConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoxID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellCoreServer).DelBoxConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShellCore_DelBoxConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellCoreServer).DelBoxConfig(ctx, req.(*BoxID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShellCore_ModifyBoxConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoxSetting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellCoreServer).ModifyBoxConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShellCore_ModifyBoxConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellCoreServer).ModifyBoxConfig(ctx, req.(*BoxSetting))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShellCore_LoginBox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoginRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShellCoreServer).LoginBox(m, &grpc.GenericServerStream[LoginRequest, BoxInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellCore_LoginBoxServer = grpc.ServerStreamingServer[BoxInfo]

func _ShellCore_QueryBoxList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellCoreServer).QueryBoxList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShellCore_QueryBoxList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellCoreServer).QueryBoxList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShellCore_QueryShellCoreInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellCoreServer).QueryShellCoreInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShellCore_QueryShellCoreInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellCoreServer).QueryShellCoreInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShellCore_UploadDebugInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDebugInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellCoreServer).UploadDebugInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShellCore_UploadDebugInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellCoreServer).UploadDebugInfo(ctx, req.(*UploadDebugInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShellCore_ConnectNearbyBox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectNearbyBoxRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShellCoreServer).ConnectNearbyBox(m, &grpc.GenericServerStream[ConnectNearbyBoxRequest, ConnectNearbyBoxReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellCore_ConnectNearbyBoxServer = grpc.ServerStreamingServer[ConnectNearbyBoxReply]

func _ShellCore_DialBoxService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DialBoxServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShellCoreServer).DialBoxService(m, &grpc.GenericServerStream[DialBoxServiceRequest, DialBoxServiceReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellCore_DialBoxServiceServer = grpc.ServerStreamingServer[DialBoxServiceReply]

func _ShellCore_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellCoreServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShellCore_Exit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellCoreServer).Exit(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShellCore_DialTokenNetwork_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DialTokenNetworkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShellCoreServer).DialTokenNetwork(m, &grpc.GenericServerStream[DialTokenNetworkRequest, DialTokenNetworkReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellCore_DialTokenNetworkServer = grpc.ServerStreamingServer[DialTokenNetworkReply]

// ShellCore_ServiceDesc is the grpc.ServiceDesc for ShellCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShellCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "space.heiyu.hportal.shell.ShellCore",
	HandlerType: (*ShellCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DelBoxConfig",
			Handler:    _ShellCore_DelBoxConfig_Handler,
		},
		{
			MethodName: "ModifyBoxConfig",
			Handler:    _ShellCore_ModifyBoxConfig_Handler,
		},
		{
			MethodName: "QueryBoxList",
			Handler:    _ShellCore_QueryBoxList_Handler,
		},
		{
			MethodName: "QueryShellCoreInfo",
			Handler:    _ShellCore_QueryShellCoreInfo_Handler,
		},
		{
			MethodName: "UploadDebugInfo",
			Handler:    _ShellCore_UploadDebugInfo_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _ShellCore_Exit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoginBox",
			Handler:       _ShellCore_LoginBox_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ConnectNearbyBox",
			Handler:       _ShellCore_ConnectNearbyBox_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DialBoxService",
			Handler:       _ShellCore_DialBoxService_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DialTokenNetwork",
			Handler:       _ShellCore_DialTokenNetwork_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remote/shellapi/shellapi.proto",
}
